development:
  openai:
    service: "OpenAI"
    api_key: <%= ENV.fetch('OPENAI_API_KEY', '') %>
    model: "gpt-4o"
    temperature: 0.7
production:
  openai:
    service: "OpenAI"
    api_key: <%= ENV.fetch('OPENAI_API_KEY', '') %>
    model: "gpt-4o"
    temperature: 0.7
